[package]
name = "capitalist"
version = "0.1.0"
authors = ["Petrus Batalha <petrus.batalha1@ibm.com>"]
edition = "2018"

[dependencies]
rdkafka = { version = "0.24", features = ["cmake-build", "ssl", "gssapi"] }
envy = "0.4.1"
serde = { version = "1.0", features = ["derive"] }
