[package]
name = "capitalist"
version = "0.1.0"
authors = ["Petrus Batalha <petrus.batalha1@ibm.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
futures = "0.3"
byteorder = "1.0.0"
error-chain = "0.12.0"
log = "0.4.6"
config = "0.10.1"
tokio = { version = "0.2", features = ["macros", "tcp", "dns", "io-util"] }
serde = { version = "1.0.114", features = ["derive"] }
rdkafka = { version = "0.24", features = ["cmake-build", "ssl", "gssapi"] }