bootstrap_servers="pkc-ldjyd.southamerica-east1.gcp.confluent.cloud:9092"
security_protocol="SASL_SSL"
sasl_mechanisms="PLAIN"
sasl_username="EEXFVX3X73RDEE7T"
sasl_password="PIbLTWpxgSGhrQF252AnxIbAKanBUV16c3ngCSu3QMiYQx+z57oomODDL0VJvb0i"
topics="__consumer_offset"
group_id="manager"