apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  labels: 
    app: kafka-exporter
  name: kafka-exporter
  namespace: pfl2
spec: 
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector: 
    matchLabels: 
      app: kafka-exporter
  strategy: 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app: kafka-exporter
    spec: 
      containers:
        args:
            - --kafka.server=10.223.42.79:31976
            - --sasl.enabled
            - --sasl.username="token"
            - --sasl.password="nNanMETnoRuTASYm9_k3TwqTXVEhN6a9mwRSzUPhvGDQ"
            - --tls.enabled
            - --tls.ca-file=/etc/tls-certs/ca-file
            - --tls.cert-file=/etc/tls-certs/cert-file
            - --tls.key-file=/etc/tls-certs/key-file
            {{- end }}
            {{- if .Values.kafkaExporter.log }}
            - --log.level={{ .Values.kafkaExporter.log.level }}
            {{- if .Values.kafkaExporter.log.enableSarama }}
            - --log.enable-sarama
            {{- end }}
            {{- end }}
        - image: danielqsj/kafka-exporter
          imagePullPolicy: IfNotPresent
          livenessProbe: 
            failureThreshold: 2
            initialDelaySeconds: 120
            periodSeconds: 3
            successThreshold: 1
            tcpSocket: 
              port: 8080
            timeoutSeconds: 1
          name: kafka-exporter
          ports: 
            - containerPort: 8080
              protocol: TCP
          readinessProbe: 
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            tcpSocket: 
              port: 8080
            timeoutSeconds: 1
      serviceAccount: pfl2
      serviceAccountName: pfl2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-exporter
  name: kafka-exporter
  namespace: pfl2
spec:
  ports:
  - name: http
    port: 9308
    protocol: TCP
    targetPort: 9308
  selector:
    app: kafka-exporter
  type: NodePort